### PR TITLE
Issue-232: Fix instrument type parsing for NextSeq2k and iSeq

### PR DESCRIPTION
**Pull request by ezralanglois**
This resolves issue #232 

- Added unit tests for RunParameters.xml parsing for both iSeq and NextSeq2k
- Added missing enum for NextSeq2k
- Fixed parsing of RunParameters.xml instrument_type field in iSeq and NextSeq2k (Issue 232)

### CODE REVIEW

**Comment by ezralanglois** [comment]
All tests pass: https://travis-ci.org/github/Illumina/interop

Need to fix linux status

**Comment by ezralanglois** [comment]
@jsvieceli I may need your help to reinstall travis as an app for this repo.

**Comment by jsvieceli** [comment]
> @jsvieceli I may need your help to reinstall travis as an app for this repo.

Of course.  What do you need me to do?

**Review by jsvieceli — APPROVED** [review]

**Comment by ezralanglois** [comment]
Add travis as a integration to interop. I don't have the permissions.

**Comment by ezralanglois** [comment]
Oh nice, thanks @jsvieceli! looks like it is working now. I just updated the version history and they both kicked off.

**Comment by ezralanglois** [comment]
Travis failed to pass due to API changes, just implemented those

**Pull request merged**
